---
name: PHP Unit Tests

on:
  push:
    branches:
      - trunk
      - 'release/**'
    paths:
      - '.github/workflows/php-test.yml'
      - '**/*.php'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'
      - '!plugins/**'
  pull_request:
    paths:
      - '.github/workflows/php-test.yml'
      - '**/*.php'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'
      - '!plugins/**'
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions: {}

env:
  WP_CORE_DIR: /tmp/wordpress
  WP_TESTS_DIR: /tmp/wordpress-tests-lib
  WP_ENVIRONMENT_TYPE: local

jobs:
  unit-tests:
    name: "Performance Lab / PHP ${{ matrix.environment.php }} / WP ${{ matrix.environment.wp }} ${{ 'true' == matrix.multisite && '/ Multisite' || ''}}"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mysql:
        image: mariadb:latest
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
          MARIADB_DATABASE: wordpress_test
          MARIADB_MYSQL_LOCALHOST_USER: 1
          MARIADB_MYSQL_LOCALHOST_GRANTS: USAGE
        ports:
          - 3306
        options: --health-cmd="healthcheck.sh --su-mysql --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        multisite: ['false', 'true']
        environment: [
          { "php": "7.0", "phpunit": "6", "wp": "latest" },
          { "php": "7.1", "phpunit": "7", "wp": "latest" },
          { "php": "7.2", "phpunit": "7", "wp": "latest" },
          { "php": "7.3", "phpunit": "7", "wp": "latest" },
          { "php": "7.4", "phpunit": "9.3", "wp": "latest" },
          { "php": "7.4", "phpunit": "9.3", "wp": "6.4" },
          { "php": "8.0", "phpunit": "9.3", "wp": "latest" },
          { "php": "8.1", "phpunit": "9.6", "wp": "latest" },
          { "php": "8.2", "phpunit": "9.6", "wp": "latest" },
          { "php": "8.3", "phpunit": "9.6", "wp": "trunk" }
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup WP tests
        uses: ./.github/actions/setup-wp-tests
        with:
          wp: ${{ matrix.environment.wp }}
          php: ${{ matrix.environment.php }}
          phpunit: ${{ matrix.environment.phpunit }}
          mysql-port: ${{ job.services.mysql.ports['3306'] }}

      - name: Run ${{ 'true' == matrix.multisite && 'Multisite' || 'Single Site' }} tests
        shell: bash
        run: |
          phpunit ${{ 'true' == matrix.multisite && '--exclude-group=ms-excluded' || '' }} --verbose
        working-directory:  ${{ env.WP_CORE_DIR }}/src/wp-content/plugins/performance
        env:
          WP_MULTISITE: ${{ 'true' == matrix.multisite && 1 || 0 }}
